SELECT
UCASE(CONCAT(E.FIRST_NAME, ' ', E.LAST_NAME)) `Nome completo`,
JH.START_DATE `Data de início`,
E.SALARY Salário
FROM hr.job_history AS JH
INNER JOIN hr.jobs as J
ON JH.JOB_ID = J.JOB_ID
INNER JOIN hr.employees AS E
ON JH.EMPLOYEE_ID = E.EMPLOYEE_ID
WHERE MONTH(JH.START_DATE) BETWEEN 1 AND 3
ORDER BY 1, 2;
